
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const CALL_PRODUCT_LISTING_API = 'CALL_PRODUCT_LISTING_API'
export const ADD_TO_CART = 'ADD_TO_CART'
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART'
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART'
export const SET_TOTAL_ITEMS_IN_CART = 'SET_TOTAL_ITEMS_IN_CART'
